// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 72999ebd2f
// Version Date: Wed Mar 17 08:36:51 UTC 2021

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "todo"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC TodoServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.TodoServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// todo

		create: grpctransport.NewServer(
			endpoints.CreateEndpoint,
			DecodeGRPCCreateRequest,
			EncodeGRPCCreateResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the TodoServer interface
type grpcServer struct {
	create grpctransport.Handler
}

// Methods for grpcServer to implement TodoServer interface

func (s *grpcServer) Create(ctx context.Context, req *pb.CreateRequest) (*pb.CreateResponse, error) {
	_, rep, err := s.create.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.CreateResponse), nil
}

// Server Decode

// DecodeGRPCCreateRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC create request to a user-domain create request. Primarily useful in a server.
func DecodeGRPCCreateRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.CreateRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCCreateResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain create response to a gRPC create reply. Primarily useful in a server.
func EncodeGRPCCreateResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.CreateResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
