// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 72999ebd2f
// Version Date: Wed Mar 17 08:36:51 UTC 2021

package svc

// This file provides server-side bindings for the HTTP transport.
// It utilizes the transport/http.Server.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"strconv"
	"strings"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"

	"context"

	httptransport "github.com/go-kit/kit/transport/http"
	"github.com/gorilla/mux"
	"github.com/pkg/errors"

	// This service
	pb "todo"
)

const contentType = "application/json; charset=utf-8"

var (
	_ = fmt.Sprint
	_ = bytes.Compare
	_ = strconv.Atoi
	_ = httptransport.NewServer
	_ = ioutil.NopCloser
	_ = pb.NewTodoClient
	_ = io.Copy
	_ = errors.Wrap
)

// MakeHTTPHandler returns a handler that makes a set of endpoints available
// on predefined paths.
func MakeHTTPHandler(endpoints Endpoints, options ...httptransport.ServerOption) http.Handler {
	serverOptions := []httptransport.ServerOption{
		httptransport.ServerBefore(headersToContext),
		httptransport.ServerErrorEncoder(errorEncoder),
		httptransport.ServerAfter(httptransport.SetContentType(contentType)),
	}
	serverOptions = append(serverOptions, options...)
	m := mux.NewRouter()

	if endpoints.HasHttpHandlerFunc("CreateTodo") {
		m.Methods("POST").Path("/todo/").HandlerFunc(endpoints.GetHttpHandlerFunc("CreateTodo"))
	} else {
		m.Methods("POST").Path("/todo/").Handler(httptransport.NewServer(
			endpoints.CreateTodoEndpoint,
			endpoints.GetHttpRequestDecoder("CreateTodo", DecodeHTTPCreateTodoZeroRequest),
			endpoints.GetHttpResponseEncoder("CreateTodo", EncodeHTTPGenericResponse),
			append(serverOptions, endpoints.GetHttpServerOptions("CreateTodo")...)...,
		))
	}

	if endpoints.HasHttpHandlerFunc("GetAll") {
		m.Methods("GET").Path("/todo").HandlerFunc(endpoints.GetHttpHandlerFunc("GetAll"))
	} else {
		m.Methods("GET").Path("/todo").Handler(httptransport.NewServer(
			endpoints.GetAllEndpoint,
			endpoints.GetHttpRequestDecoder("GetAll", DecodeHTTPGetAllZeroRequest),
			endpoints.GetHttpResponseEncoder("GetAll", EncodeHTTPGenericResponse),
			append(serverOptions, endpoints.GetHttpServerOptions("GetAll")...)...,
		))
	}

	if endpoints.HasHttpHandlerFunc("GetTodo") {
		m.Methods("GET").Path("/todo/{id}").HandlerFunc(endpoints.GetHttpHandlerFunc("GetTodo"))
	} else {
		m.Methods("GET").Path("/todo/{id}").Handler(httptransport.NewServer(
			endpoints.GetTodoEndpoint,
			endpoints.GetHttpRequestDecoder("GetTodo", DecodeHTTPGetTodoZeroRequest),
			endpoints.GetHttpResponseEncoder("GetTodo", EncodeHTTPGenericResponse),
			append(serverOptions, endpoints.GetHttpServerOptions("GetTodo")...)...,
		))
	}

	if endpoints.HasHttpHandlerFunc("DeleteTodo") {
		m.Methods("DELETE").Path("/todo/{id}").HandlerFunc(endpoints.GetHttpHandlerFunc("DeleteTodo"))
	} else {
		m.Methods("DELETE").Path("/todo/{id}").Handler(httptransport.NewServer(
			endpoints.DeleteTodoEndpoint,
			endpoints.GetHttpRequestDecoder("DeleteTodo", DecodeHTTPDeleteTodoZeroRequest),
			endpoints.GetHttpResponseEncoder("DeleteTodo", EncodeHTTPGenericResponse),
			append(serverOptions, endpoints.GetHttpServerOptions("DeleteTodo")...)...,
		))
	}
	return m
}

// ErrorEncoder writes the error to the ResponseWriter, by default a content
// type of application/json, a body of json with key "error" and the value
// error.Error(), and a status code of 500. If the error implements Headerer,
// the provided headers will be applied to the response. If the error
// implements json.Marshaler, and the marshaling succeeds, the JSON encoded
// form of the error will be used. If the error implements StatusCoder, the
// provided StatusCode will be used instead of 500.
func errorEncoder(_ context.Context, err error, w http.ResponseWriter) {
	body, _ := json.Marshal(errorWrapper{Error: err.Error()})
	if marshaler, ok := err.(json.Marshaler); ok {
		if jsonBody, marshalErr := marshaler.MarshalJSON(); marshalErr == nil {
			body = jsonBody
		}
	}
	w.Header().Set("Content-Type", contentType)
	if headerer, ok := err.(httptransport.Headerer); ok {
		for k := range headerer.Headers() {
			w.Header().Set(k, headerer.Headers().Get(k))
		}
	}
	code := http.StatusInternalServerError
	if sc, ok := err.(httptransport.StatusCoder); ok {
		code = sc.StatusCode()
	}
	w.WriteHeader(code)
	w.Write(body)
}

type errorWrapper struct {
	Error string `json:"error"`
}

// httpError satisfies the Headerer and StatusCoder interfaces in
// package github.com/go-kit/kit/transport/http.
type httpError struct {
	error
	statusCode int
	headers    map[string][]string
}

func (h httpError) StatusCode() int {
	return h.statusCode
}

func (h httpError) Headers() http.Header {
	return h.headers
}

// Server Decode

// DecodeHTTPCreateTodoZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded createtodo request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPCreateTodoZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.CreateTodoRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{errors.Wrapf(err, "request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	return &req, err
}

// DecodeHTTPGetAllZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded getall request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPGetAllZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.GetAllRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{errors.Wrapf(err, "request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	return &req, err
}

// DecodeHTTPGetTodoZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded gettodo request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPGetTodoZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.GetTodoRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{errors.Wrapf(err, "request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	IdGetTodoStr := pathParams["id"]
	IdGetTodo, err := strconv.ParseUint(IdGetTodoStr, 10, 64)
	if err != nil {
		return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting IdGetTodo from path, pathParams: %v", pathParams))
	}
	req.Id = IdGetTodo

	return &req, err
}

// DecodeHTTPDeleteTodoZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded deletetodo request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPDeleteTodoZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.DeleteTodoRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{errors.Wrapf(err, "request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	IdDeleteTodoStr := pathParams["id"]
	IdDeleteTodo, err := strconv.ParseUint(IdDeleteTodoStr, 10, 64)
	if err != nil {
		return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting IdDeleteTodo from path, pathParams: %v", pathParams))
	}
	req.Id = IdDeleteTodo

	return &req, err
}

// EncodeHTTPGenericResponse is a transport/http.EncodeResponseFunc that encodes
// the response as JSON to the response writer. Primarily useful in a server.
func EncodeHTTPGenericResponse(_ context.Context, w http.ResponseWriter, response interface{}) error {
	marshaller := jsonpb.Marshaler{
		EmitDefaults: false,
		OrigName:     true,
	}

	return marshaller.Marshal(w, response.(proto.Message))
}

// Helper functions

func headersToContext(ctx context.Context, r *http.Request) context.Context {
	for k := range r.Header {
		// The key is added both in http format (k) which has had
		// http.CanonicalHeaderKey called on it in transport as well as the
		// strings.ToLower which is the grpc metadata format of the key so
		// that it can be accessed in either format
		ctx = context.WithValue(ctx, k, r.Header.Get(k))
		ctx = context.WithValue(ctx, strings.ToLower(k), r.Header.Get(k))
	}

	// Tune specific change.
	// also add the request url
	ctx = context.WithValue(ctx, "request-url", r.URL.Path)
	ctx = context.WithValue(ctx, "transport", "HTTPJSON")

	return ctx
}
